# Generated by Django 4.0.2 on 2022-05-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_coach',
            field=models.BooleanField(default=False),
        ),
    ]
