# Generated by Django 4.0.2 on 2022-05-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='petitsurnommigion',
            field=models.CharField(default='migion', max_length=128),
        ),
    ]
