# Generated by Django 4.0.2 on 2022-05-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_petitsurnommigion'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='promotion',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='petitsurnommigion',
            field=models.CharField(default='If youre seeing this, youre cute', max_length=128),
        ),
    ]
