# Generated by Django 4.0.2 on 2022-05-17 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_profile_picture_customuser_promotion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='promotion',
        ),
    ]
