# Generated by Django 4.0.2 on 2022-05-17 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_promotion'),
        ('users', '0006_remove_customuser_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='promotion',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='polls.promotion'),
        ),
    ]
