# Generated by Django 4.0.2 on 2022-05-17 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_promotion'),
        ('users', '0008_alter_customuser_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.promotion'),
        ),
    ]
