# Generated by Django 4.0.2 on 2022-05-24 13:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='uniqueID',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
