# Generated by Django 4.0.2 on 2022-05-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_customuser_uniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
