# Generated by Django 4.0.2 on 2022-05-17 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote_list',
            name='voted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vote',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.choice'),
        ),
        migrations.AddField(
            model_name='vote',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.poll'),
        ),
        migrations.AddField(
            model_name='vote',
            name='voted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_per_group',
            name='groups',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.groups'),
        ),
        migrations.AddField(
            model_name='user_per_group',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poll',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learner_project',
            name='group_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.group_project'),
        ),
        migrations.AddField(
            model_name='learner_project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groups',
            name='group_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.group_project'),
        ),
        migrations.AddField(
            model_name='groups',
            name='learner_project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.learner_project'),
        ),
        migrations.AddField(
            model_name='choice',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.poll'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('poll', 'voted_by')},
        ),
    ]
