# Generated by Django 4.0.2 on 2022-05-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_groups_user_learner_project_group_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
