# Generated by Django 4.0.2 on 2022-05-24 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_vote_list_whishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learner_project',
            name='database_schema_picture',
        ),
        migrations.RemoveField(
            model_name='learner_project',
            name='mockup_picture',
        ),
    ]
