# Generated by Django 4.0.2 on 2022-05-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_learner_project_database_schema_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner_project',
            name='database_schema_picture',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='learner_project',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='learner_project',
            name='mockup_picture',
            field=models.TextField(default=''),
        ),
    ]
