# Generated by Django 4.0.2 on 2022-05-17 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('polls', '0006_alter_groups_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='user',
            field=models.ManyToManyField(related_name='+', through='polls.User_per_group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='user_per_group',
            name='user',
        ),
        migrations.AddField(
            model_name='user_per_group',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
