# Generated by Django 4.0.2 on 2022-05-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_learner_project_database_schema_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner_project',
            name='database_schema_picture',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='learner_project',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='learner_project',
            name='mockup_picture',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
