# Generated by Django 4.0.2 on 2022-05-26 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_learner_project_database_schema_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote_list',
            old_name='voted_by',
            new_name='user',
        ),
    ]
