# Generated by Django 4.0.2 on 2022-05-17 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0007_alter_groups_user_remove_user_per_group_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner_project',
            name='group_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.group_project'),
        ),
        migrations.AlterField(
            model_name='user_per_group',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
