# Generated by Django 4.0.2 on 2022-05-26 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_rename_voted_by_vote_list_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote_list',
            old_name='user',
            new_name='voted_by',
        ),
    ]
