# Generated by Django 4.0.2 on 2022-05-17 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_user_per_group_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='user',
        ),
    ]
