# Generated by Django 4.0.2 on 2022-05-27 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0009_rename_user_vote_list_voted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_per_promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.promotion')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
