# Generated by Django 4.0.2 on 2022-05-30 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_user_per_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote_list',
            name='asigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.groups'),
        ),
    ]
