# Generated by Django 4.0.2 on 2022-05-17 08:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0010_remove_groups_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_per_group',
            name='user',
        ),
        migrations.AddField(
            model_name='user_per_group',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
