# Generated by Django 4.0.2 on 2022-05-17 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_vote_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote_list',
            name='voted_for',
        ),
        migrations.AddField(
            model_name='vote_list',
            name='asigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.group_project'),
        ),
    ]
